[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "CJ Vines",email = "cjvines56@tamu.edu"},
    {name = "Christian Casteel",email = "christiancasteel@tamu.edu"},
    {name = "Kosi Ezewudo",email = "exewudokositoni@tamu.edu"}
    ]
readme = "README.md"
requires-python = ">=3.13, <3.15"
dependencies = [
    "openpyxl (>=3.1.5,<4.0.0)",
    "langchain-ollama (>=1.0.1,<2.0.0)",
    "langchain (>=1.2.6,<2.0.0)",
    "langchain-chroma (>=1.1.0,<2.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "langchain-community (>=0.4.1,<0.5.0)",
    "langchain-text-splitters (>=1.1.0,<2.0.0)",
    "langchain-google-genai (>=4.2.0,<5.0.0)",
    "sentence-transformers (>=5.2.0,<6.0.0)",
    "langchain-huggingface (>=1.2.0,<2.0.0)",
    "langgraph (>=1.0.7,<2.0.0)",
    "ragas (>=0.4.3,<0.5.0)",
    "datasets (>=4.5.0,<5.0.0)",
    "langchain-openai (>=1.1.7,<2.0.0)",
    "langsmith (>=0.6.9,<0.7.0)",
    "langmem (>=0.0.30,<0.0.31)",
]


[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)",
    "ruff (>=0.13.1,<0.14.0)"
]
