services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8081:8080"
      - "50052:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: text2vec-openai
      GRPC_PORT: 50051
      LIMIT_RESOURCES: "true"
      HNSW_VECTOR_CACHE_MAX_OBJECTS: 100000
      CLUSTER_HOSTNAME: acf0d04ae54d

volumes:
  weaviate_data:
